"""empty message

Revision ID: 0294ed5fdc57
Revises: ff64289394ef
Create Date: 2026-01-14 12:38:52.595911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0294ed5fdc57'
down_revision = 'ff64289394ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_de_compra', schema=None) as batch_op:
        batch_op.alter_column('id_ubicacion',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_de_compra', schema=None) as batch_op:
        batch_op.alter_column('id_ubicacion',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
