"""empty message

Revision ID: 06a0dcc1f346
Revises: 
Create Date: 2026-01-13 23:08:24.680852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06a0dcc1f346'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Eliminar FK primero (si existe)
    op.execute("""
    ALTER TABLE ordenes_de_compra
    DROP CONSTRAINT IF EXISTS ordenes_de_compra_id_ubicacion_fkey;
    """)

    # Ahora sí, eliminar la tabla
    op.execute("""
    DROP TABLE IF EXISTS ubicaciones;
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dias_de_entrega', postgresql.ARRAY(sa.VARCHAR(length=100)), autoincrement=False, nullable=True))

    with op.batch_alter_table('ordenes_de_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_ubicacion', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('ordenes_de_compra_id_ubicacion_fkey', 'ubicaciones', ['id_ubicacion'], ['id'])

    op.create_table('inventario',
    sa.Column('id_producto', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_visualizacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], name='inventario_id_producto_fkey'),
    sa.PrimaryKeyConstraint('id', name='inventario_pkey')
    )
    op.create_table('productos_proveedores',
    sa.Column('id_proveedor', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id_producto', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], name='productos_proveedores_id_producto_fkey'),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id'], name='productos_proveedores_id_proveedor_fkey')
    )
    op.create_table('ubicaciones',
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('estatus', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_visualizacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ubicaciones_pkey')
    )
    op.drop_table('pago')
    op.drop_table('movimiento_bancario')
    op.drop_table('gasto')
    op.drop_table('cuenta_banco')
    op.drop_table('categoria_gasto')
    # ### end Alembic commands ###
