"""empty message

Revision ID: 4421aad84180
Revises: af09e71404bc
Create Date: 2026-01-21 12:27:13.523145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4421aad84180'
down_revision = 'af09e71404bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('almacen',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('existencia',
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.Column('id_almacen', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_almacen'], ['almacen.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transferencia_inventario',
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.Column('id_almacen_origen', sa.UUID(), nullable=False),
    sa.Column('id_almacen_destino', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estatus', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_almacen_destino'], ['almacen.id'], ),
    sa.ForeignKeyConstraint(['id_almacen_origen'], ['almacen.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordenes_de_compra', schema=None) as batch_op:
        batch_op.alter_column('id_ubicacion',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_de_compra', schema=None) as batch_op:
        batch_op.alter_column('id_ubicacion',
               existing_type=sa.UUID(),
               nullable=True)

    op.drop_table('transferencia_inventario')
    op.drop_table('existencia')
    op.drop_table('almacen')
    # ### end Alembic commands ###
