"""empty message

Revision ID: 5c15638ec2d4
Revises: 60ea9b7d89d8
Create Date: 2026-01-14 09:37:20.372507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c15638ec2d4'
down_revision = '60ea9b7d89d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ubicaciones',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordenes_de_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_ubicacion', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'ubicaciones', ['id_ubicacion'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_de_compra', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_ubicacion')

    op.drop_table('ubicaciones')
    # ### end Alembic commands ###
