"""empty message

Revision ID: 60ea9b7d89d8
Revises: 700db0c9a14e
Create Date: 2026-01-14 09:28:09.947142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ea9b7d89d8'
down_revision = '700db0c9a14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dias_de_entrega', sa.ARRAY(sa.String(length=100)), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_column('dias_de_entrega')

    # ### end Alembic commands ###
