"""empty message

Revision ID: 6d400febc76f
Revises: 9ff0189e5be9
Create Date: 2026-01-14 15:37:41.184547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d400febc76f'
down_revision = '9ff0189e5be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_comprobante', sa.String(length=255), nullable=True))

    with op.batch_alter_table('ordenes_de_compra', schema=None) as batch_op:
        batch_op.alter_column('id_ubicacion',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_de_compra', schema=None) as batch_op:
        batch_op.alter_column('id_ubicacion',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.drop_column('archivo_comprobante')

    # ### end Alembic commands ###
