"""empty message

Revision ID: 700db0c9a14e
Revises: 06a0dcc1f346
Create Date: 2026-01-13 23:10:43.562809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '700db0c9a14e'
down_revision = '06a0dcc1f346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_gasto',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuenta_banco',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('numero_cuenta', sa.String(length=50), nullable=False),
    sa.Column('banco', sa.String(length=255), nullable=False),
    sa.Column('saldo_inicial', sa.Float(), nullable=False),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gasto',
    sa.Column('id_categoria', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estatus', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria_gasto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento_bancario',
    sa.Column('id_cuenta', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cuenta'], ['cuenta_banco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id_gasto', sa.UUID(), nullable=True),
    sa.Column('id_orden_de_compra', sa.UUID(), nullable=True),
    sa.Column('id_cuenta', sa.UUID(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estatus', sa.String(length=50), nullable=True),
    sa.Column('referencia', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cuenta'], ['cuenta_banco.id'], ),
    sa.ForeignKeyConstraint(['id_gasto'], ['gasto.id'], ),
    sa.ForeignKeyConstraint(['id_orden_de_compra'], ['ordenes_de_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('inventario')
    op.drop_table('productos_proveedores')
    with op.batch_alter_table('ordenes_de_compra', schema=None) as batch_op:
        batch_op.drop_column('id_ubicacion')

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_column('dias_de_entrega')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dias_de_entrega', postgresql.ARRAY(sa.VARCHAR(length=100)), autoincrement=False, nullable=True))

    with op.batch_alter_table('ordenes_de_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_ubicacion', sa.UUID(), autoincrement=False, nullable=False))

    op.create_table('productos_proveedores',
    sa.Column('id_proveedor', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id_producto', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], name='productos_proveedores_id_producto_fkey'),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id'], name='productos_proveedores_id_proveedor_fkey')
    )
    op.create_table('inventario',
    sa.Column('id_producto', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_visualizacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], name='inventario_id_producto_fkey'),
    sa.PrimaryKeyConstraint('id', name='inventario_pkey')
    )
    op.drop_table('pago')
    op.drop_table('movimiento_bancario')
    op.drop_table('gasto')
    op.drop_table('cuenta_banco')
    op.drop_table('categoria_gasto')
    # ### end Alembic commands ###
