"""empty message

Revision ID: a03dfada2f65
Revises: 9cff55f7b8e6
Create Date: 2026-01-15 12:39:12.457096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03dfada2f65'
down_revision = '9cff55f7b8e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuenta_banco', schema=None) as batch_op:
        batch_op.drop_column('saldo_actual')

    with op.batch_alter_table('ordenes_de_compra', schema=None) as batch_op:
        batch_op.alter_column('id_ubicacion',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_de_compra', schema=None) as batch_op:
        batch_op.alter_column('id_ubicacion',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('cuenta_banco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
