"""empty message

Revision ID: af09e71404bc
Revises: dee6bb2acf65
Create Date: 2026-01-15 16:34:53.507291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af09e71404bc'
down_revision = 'dee6bb2acf65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuenta_banco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_actual', sa.Float()))

    with op.batch_alter_table('ordenes_de_compra', schema=None) as batch_op:
        batch_op.alter_column('id_ubicacion',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_de_compra', schema=None) as batch_op:
        batch_op.alter_column('id_ubicacion',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('cuenta_banco', schema=None) as batch_op:
        batch_op.drop_column('saldo_actual')

    # ### end Alembic commands ###
