"""empty message

Revision ID: f8f231fd593f
Revises: 6d400febc76f
Create Date: 2026-01-15 12:08:05.993549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f231fd593f'
down_revision = '6d400febc76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_de_compra', schema=None) as batch_op:
        batch_op.alter_column('id_ubicacion',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_de_compra', schema=None) as batch_op:
        batch_op.alter_column('id_ubicacion',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
